name: crud-fastapi
services:
  crud-fastapi:
    image: ${IMAGE_NAME}
    hostname: crud-fastapi
    container_name: crud-fastapi
    ports:
      - "8081:8081"
    networks:
      - vps-network
    env_file:
      - ../local.env
    volumes:
      - ${FILES_STORAGE_DIRECTORY}:/opt/crud-fastapi/files_storage_directory

networks:
  vps-network:
    name: vps-network
    driver: bridge

